name: Next.js Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create .env file with placeholder values
        run: |
          touch .env
          echo "DATABASE_URL=placeholder" >> .env
          echo "DIRECT_URL=placeholder" >> .env
          echo "RESEND_API_KEY=placeholder-key" >> .env
          echo "AWS_BUCKET_NAME=placeholder-name" >> .env
          echo "AWS_REGION=placeholder-region" >> .env
          echo "AWS_ACCESS_KEY=placeholder-key" >> .env
          echo "AWS_SECRET_ACCESS_KEY=placeholder-secret-key" >> .env
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=placeholder-key" >> .env
          echo "STRIPE_SECRET_KEY=placeholder-secret-key" >> .env
          echo "STRIPE_WEBHOOK_SECRET=placeholder-secret-key" >> .env

      - name: Install dependencies
        run: |
          npm ci
          npm run postinstall

      - name: Build Next.js app
        run: npm run build
